name: ARP Spoofing Attack and Capture

on:
  push:
    branches:
      - main

jobs:
  arp-spoof-attack:
    runs-on: self-hosted  # Assuming self-hosted runner with SSH access to the target

    steps:
      - name: SSH into Target VM and Execute ARP Spoofing
        run: |
          ssh rb@172.30.117.123 "sudo /home/rb/arp_spoof.sh 172.30.124.62"

      - name: Check if capture file exists on Target VM
        run: |
          ssh rb@172.30.117.123 "ls -l /home/rb/"

      - name: Download capture file from Target VM
        run: |
          scp rb@172.30.117.123:/home/rb/arp_capture.pcap ./arp_capture.pcap

      - name: Upload pcap file for Analysis
        uses: actions/upload-artifact@v4
        with:
          name: arp-traffic-capture
          path: ./arp_capture.pcap
          retention-days: 5
