name: dnsspo Attack Automation

on:
  push:
    branches:
      - main

jobs:
  mitm_attack:
    runs-on: [self-hosted, cicd-dnsspo]  # Runner sur la machine CI/CD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ATTACKER_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.TARGET_IP }} >> ~/.ssh/known_hosts
     
      - name: SSH into Kali VM
        run: |
          ssh -o StrictHostKeyChecking=no rb@${{ secrets.ATTACKER_IP }} 'ls -la'

      - name: Deploy attack script to Attacker Machine
        run: |
          scp ./arp_spoof.sh rb@${{ secrets.ATTACKER_IP }}:/home/rb/
          ssh rb@${{ secrets.ATTACKER_IP }} "chmod +x /home/rb/arp_spoof.sh"

      - name: Execute MITM Attack
        run: |
          ssh rb@${{ secrets.ATTACKER_IP }} "sudo /home/rb/arp_spoof.sh ${{ secrets.TARGET_IP }}"

      - name: Collect Attack Logs
        run: |
          ssh rb@${{ secrets.ATTACKER_IP }} "cat /home/rb/arp_attack_logs.txt" > attack_results.txt

      - name: Upload Attack Results
        uses: actions/upload-artifact@v4
        with:
          name: mitm-attack-results
          path: attack_results.txt
          retention-days: 5

      - name: Deploy Detection Script to Target Machine
        run: |
          scp ./detect_mitm.sh rb@${{ secrets.TARGET_IP }}:/home/rb/
          ssh rb@${{ secrets.TARGET_IP }} "chmod +x /home/rb/detect_mitm.sh"

      - name: Execute MITM Detection on Target Machine
        run: |
          ssh rb@${{ secrets.TARGET_IP }} "sudo su /home/rb/detect_mitm.sh"

      - name: Deploy Protection Script to Target Machine
        run: |
          scp ./protect_mitm.sh rb@${{ secrets.TARGET_IP }}:/home/rb/
          ssh rb@${{ secrets.TARGET_IP }} "chmod +x /home/rb/protect_mitm.sh"

      - name: Execute MITM Protection on Target Machine
        run: |
          ssh rb@${{ secrets.TARGET_IP }} "sudo /home/rb/protect_mitm.sh"
