name: MITM Attack Automation

on:
  push:
    branches:
      - main

jobs:
  mitm_attack:
    runs-on: [self-hosted, cicd-mitm]  # Runner sur la machine CI/CD MITM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_MITM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ATTACKER_IP_MITM }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.TARGET_IP_MITM }} >> ~/.ssh/known_hosts

      # ✅ Start Detection Before the Attack
      - name: Start MITM Detection on Target Machine
        run: |
          ssh rb@${{ secrets.TARGET_IP_MITM }} "nohup sudo /home/rb/detect_mitm.sh > /home/rb/detect_log.txt 2>&1 &"
      
      # ✅ Deploy Attack Script to Attacker Machine
      - name: Deploy attack script to Attacker Machine
        run: |
          scp mitm_scripts/arp_spoof.sh rb@${{ secrets.ATTACKER_IP_MITM }}:/home/rb/
          ssh rb@${{ secrets.ATTACKER_IP_MITM }} "chmod +x /home/rb/arp_spoof.sh"

      # ✅ Execute MITM Attack
      - name: Execute MITM Attack
        run: |
          ssh rb@${{ secrets.ATTACKER_IP_MITM }} "sudo /home/rb/arp_spoof.sh ${{ secrets.TARGET_IP_MITM }}"

      # ✅ Stop Detection & Collect Logs
      - name: Stop Detection & Collect Logs
        run: |
          ssh rb@${{ secrets.TARGET_IP_MITM }} "sudo pkill -f detect_mitm.sh"
          scp rb@${{ secrets.TARGET_IP_MITM }}:/home/rb/detect_log.txt detection_results.txt

      # ✅ Upload Detection Results
      - name: Upload Detection Results
        uses: actions/upload-artifact@v4
        with:
          name: mitm-detection-results
          path: detection_results.txt
          retention-days: 5

      # ✅ Deploy Protection Script to Target Machine
      - name: Deploy Protection Script to Target Machine
        run: |
          scp mitm_scripts/protect_mitm.sh rb@${{ secrets.TARGET_IP_MITM }}:/home/rb/
          ssh rb@${{ secrets.TARGET_IP_MITM }} "chmod +x /home/rb/protect_mitm.sh"
    
      # ✅ Execute MITM Protection on Target Machine
      - name: Execute MITM Protection on Target Machine
        run: |
          ssh rb@${{ secrets.TARGET_IP_MITM }} "sudo /home/rb/protect_mitm.sh"
