name: Test SSH to Kali VM

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: self-hosted  # Adjust if you're using GitHub-hosted runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code to access arp_spoof.sh

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.30.117.123 >> ~/.ssh/known_hosts

      - name: SSH into Kali VM
        run: |
          ssh -o StrictHostKeyChecking=no rb@172.30.117.123 'ls -la'

      - name: Deploy attack script to Kali machine
        run: |
          scp arp_spoof.sh rb@172.30.117.123:/home/rb/
          ssh rb@172.30.117.123 "chmod +x /home/rb/arp_spoof.sh"

      - name: Execute ARP spoofing attack
        run: |
          ssh rb@172.30.117.123 "sudo /home/rb/arp_spoof.sh 172.30.124.62"

      - name: Collect and store results
        run: |
          ssh rb@172.30.117.123 "cat /home/rb/arp_attack_logs.txt" > attack_results.txt
          
      - name: Upload attack results
        uses: actions/upload-artifact@v4
        with:
          name: arp-spoof-results
          path: attack_results.txt
          retention-days: 5
